name: Maven构建

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: 使用Maven构建
      run: mvn -B package --file pom.xml

    - name: 上传构建产物
      uses: actions/upload-artifact@v3
      with:
        name: plugin-jar
        path: target/*.jar
        retention-days: 5
